website:
  title: "Sumaya Akter"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "CV"
        href: CV_Sumaya.pdf

 