
project:
  type: website
  output-dir: docs
  resources:
    - CV_Sumaya.pdf

website:
  title: "About Me"
  site-url: https://sumayaakter739.github.io/my_amazing-code/
  favicon: img/sumaya.jpg
  navbar:
    left:
      - text: "Education"
        href: Education.qmd
      - text: "Research"
        href: research.qmd
  page-footer:
    left: "&copy; 2025"
    right: "Built with Quarto"

format:
  html:
    theme: yeti
    toc: false
    page-layout: full
