project:
  type: website
  output-dir: docs

website:
  title: "Sumaya Akter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/SumayaAkter739
      - icon: envelope
        href: mailto:sumayagbe.nstu@gmail.com

format:
  html:
    theme: flatly
