
project:
  type: website
  output-dir: docs
  resources:
    - CV_Sumaya.pdf

website:
  title: "About Me"
  site-url: https://sumayaakter739.github.io/my_amazing-code/
  favicon: img/sumaya.jpg
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "CV"
        href: CV_Sumaya.pdf
  page-footer:
    left: "&copy; 2025"
    right: "Built with Quarto"

format:
  html:
    theme: yeti
    toc: false
    page-layout: full
